### Day-14
#### Intro to Panda

In [1]:
pip install panda

Defaulting to user installation because normal site-packages is not writeable
Collecting panda
  Using cached panda-0.3.1-py3-none-any.whl
Requirement already satisfied: setuptools in c:\programdata\anaconda3\anaconda\lib\site-packages (from panda) (75.1.0)
Requirement already satisfied: requests in c:\programdata\anaconda3\anaconda\lib\site-packages (from panda) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\anaconda\lib\site-packages (from requests->panda) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\anaconda\lib\site-packages (from requests->panda) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\anaconda\lib\site-packages (from requests->panda) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\anaconda\lib\site-packages (from requests->panda) (2024.8.30)
Installing collected packages: panda
Successfully installed panda-0.3.1
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd

In [ ]:
pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

#### Head Data

In [9]:
x=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
x.head(6)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

#### Bottom data

In [10]:
x=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
x.tail(6)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.125,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.450,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.750,NaN,Q

#### Know  the data types

In [11]:
x.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

#### Founding data types

In [5]:
import pandas as pd

In [7]:

x=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
x.dtypes=='object'

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

####know the data types with index no.

In [9]:
x[x.dtypes[x.dtypes=='float64'].index]

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

#### Describe Function

In [12]:
x.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

#### Slicing Row and Columns

In [16]:
x[["Age","Fare","Name"]]
x.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

#### Know the data type with index no.

In [18]:
x[x.dtypes[x.dtypes=='float64'].index]

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [10]:
x

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
x['Aderneil']=2

x

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Aderneil
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,2
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,2

# Day-15

#### Know the name of columns

In [8]:
x=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
x.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

#### Know the data of particuar columns

In [20]:
x=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
x[['Name']]

                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
886                              Montvila, Rev. Juozas
887                       Graham, Miss. Margaret Edith
888           Johnston, Miss. Catherine Helen "Carrie"
889                              Behr, Mr. Karl Howell
890                                Dooley, Mr. Patrick

[891 rows x 1 columns]

#### Slicing Data within columns

In [21]:
x[['Fare']][4:18]

       Fare
4    8.0500
5    8.4583
6   51.8625
7   21.0750
8   11.1333
9   30.0708
10  16.7000
11  26.5500
12   8.0500
13  31.2750
14   7.8542
15  16.0000
16  29.1250
17  13.0000

Storing Sliced Data in a Varaible

In [20]:
import pandas as pd
x=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

a=x[['Fare']][4:18]  #storing data in variable "a"
a               # calling the stored data in "a"

       Fare
4    8.0500
5    8.4583
6   51.8625
7   21.0750
8   11.1333
9   30.0708
10  16.7000
11  26.5500
12   8.0500
13  31.2750
14   7.8542
15  16.0000
16  29.1250
17  13.0000

Slicing data with jump of 1

In [7]:
x[['Fare']][4:18:2]       # Here 2 is for jump of 1

       Fare
4    8.0500
6   51.8625
8   11.1333
10  16.7000
12   8.0500
14   7.8542
16  29.1250

Creating own Index

In [27]:
k=['1st','2nd','3rd','4th','5ht','6th','7th','8th','9th','10th','11th','12th','13th','14th']
pd.Series(a, index=k)

ValueError: Data must be 1-dimensional, got ndarray of shape (14, 1) instead

In [23]:
x[['Cabin','Name']]

    Cabin                                               Name
0     NaN                            Braund, Mr. Owen Harris
1     C85  Cumings, Mrs. John Bradley (Florence Briggs Th...
2     NaN                             Heikkinen, Miss. Laina
3    C123       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4     NaN                           Allen, Mr. William Henry
..    ...                                                ...
886   NaN                              Montvila, Rev. Juozas
887   B42                       Graham, Miss. Margaret Edith
888   NaN           Johnston, Miss. Catherine Helen "Carrie"
889  C148                              Behr, Mr. Karl Howell
890   NaN                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [24]:
x

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

Inserting a column with own value

In [25]:
x['kamil']=2

In [26]:
x

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,kamil
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,2
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,2

Know the data type of varaible

In [27]:
type(x)

pandas.core.frame.DataFrame

Inserting a column with value

In [33]:
x.insert(loc=3,column='rump',value=1)
x

,PassengerId,Survived,Pclass,rump,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,1,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,1,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,1,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,1,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,1,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [44]:
x

,PassengerId,Survived,Pclass,rump,Food,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,kamil
0,1,0,3,1,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,2,1,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,1,1,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,2
3,4,1,1,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
4,5,0,3,1,1,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,1,1,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,2
887,888,1,1,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,2
888,889,0,3,1,1,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,2
889,890,1,1,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,2
890,891,0,3,1,1,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,2

Creating own index own value

In [34]:
m1=pd.Series([100,200,300,400,500], index = [1,2,3,4,5])
m1

1    100
2    200
3    300
4    400
5    500
dtype: int64

In [39]:
m2=pd.Series([600,700,800,900,1000],index=[1,2,3,4,5])
m2

1     600
2     700
3     800
4     900
5    1000
dtype: int64

Combining Two data sets

In [40]:
m3=pd.concat([m1,m2])
m3

1     100
2     200
3     300
4     400
5     500
1     600
2     700
3     800
4     900
5    1000
dtype: int64

Multiplying

In [41]:
m1*m2

1     60000
2    140000
3    240000
4    360000
5    500000
dtype: int64

Add

In [42]:
m1+m2

1     700
2     900
3    1100
4    1300
5    1500
dtype: int64

Deleting Columns

In [54]:
x.drop("Cabin", axis=1)   # Deleitng temporary

,Survived,Pclass,rump,Name,Sex,Age,SibSp,Ticket,Fare,Embarked
0,0,3,1,"Braund, Mr. Owen Harris",male,22.0,1,A/5 21171,7.2500,S
1,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,PC 17599,71.2833,C
2,1,3,1,"Heikkinen, Miss. Laina",female,26.0,0,STON/O2. 3101282,7.9250,S
4,0,3,1,"Allen, Mr. William Henry",male,35.0,0,373450,8.0500,S
5,0,3,1,"Moran, Mr. James",male,NaN,0,330877,8.4583,Q
...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,"Montvila, Rev. Juozas",male,27.0,0,211536,13.0000,S
887,1,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,112053,30.0000,S
888,0,3,1,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,W./C. 6607,23.4500,S
889,1,1,1,"Behr, Mr. Karl Howell",male,26.0,0,111369,30.0000,C
890,0,3,1,"Dooley, Mr. Patrick",male,32.0,0,370376,7.7500,Q

In [55]:
x.drop("Parch", axis=1,inplace=True)

KeyError: "['Parch'] not found in axis"

In [ ]:
x

,Survived,Pclass,rump,Name,Sex,Age,SibSp,Ticket,Fare,Cabin,Embarked
0,0,3,1,"Braund, Mr. Owen Harris",male,22.0,1,A/5 21171,7.2500,NaN,S
1,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,PC 17599,71.2833,C85,C
2,1,3,1,"Heikkinen, Miss. Laina",female,26.0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,113803,53.1000,C123,S
4,0,3,1,"Allen, Mr. William Henry",male,35.0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,"Montvila, Rev. Juozas",male,27.0,0,211536,13.0000,NaN,S
887,1,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,112053,30.0000,B42,S
888,0,3,1,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,W./C. 6607,23.4500,NaN,S
889,1,1,1,"Behr, Mr. Karl Howell",male,26.0,0,111369,30.0000,C148,C
890,0,3,1,"Dooley, Mr. Patrick",male,32.0,0,370376,7.7500,NaN,Q

Deleting Row

In [52]:
x.drop(3,inplace=True)

In [53]:
x

,Survived,Pclass,rump,Name,Sex,Age,SibSp,Ticket,Fare,Cabin,Embarked
0,0,3,1,"Braund, Mr. Owen Harris",male,22.0,1,A/5 21171,7.2500,NaN,S
1,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,PC 17599,71.2833,C85,C
2,1,3,1,"Heikkinen, Miss. Laina",female,26.0,0,STON/O2. 3101282,7.9250,NaN,S
4,0,3,1,"Allen, Mr. William Henry",male,35.0,0,373450,8.0500,NaN,S
5,0,3,1,"Moran, Mr. James",male,NaN,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,"Montvila, Rev. Juozas",male,27.0,0,211536,13.0000,NaN,S
887,1,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,112053,30.0000,B42,S
888,0,3,1,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,W./C. 6607,23.4500,NaN,S
889,1,1,1,"Behr, Mr. Karl Howell",male,26.0,0,111369,30.0000,C148,C
890,0,3,1,"Dooley, Mr. Patrick",male,32.0,0,370376,7.7500,NaN,Q

Seting any thing in index

In [56]:
x.set_index('Name', inplace=True)

In [57]:
x

,Survived,Pclass,rump,Sex,Age,SibSp,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Braund, Mr. Owen Harris",0,3,1,male,22.0,1,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,1,female,38.0,1,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",1,3,1,female,26.0,0,STON/O2. 3101282,7.9250,NaN,S
"Allen, Mr. William Henry",0,3,1,male,35.0,0,373450,8.0500,NaN,S
"Moran, Mr. James",0,3,1,male,NaN,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",0,2,1,male,27.0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",1,1,1,female,19.0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",0,3,1,female,NaN,1,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",1,1,1,male,26.0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",0,3,1,male,32.0,0,370376,7.7500,NaN,Q

Reseting Index

In [58]:
x.reset_index()

,Name,Survived,Pclass,rump,Sex,Age,SibSp,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",0,3,1,male,22.0,1,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,1,female,38.0,1,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",1,3,1,female,26.0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Allen, Mr. William Henry",0,3,1,male,35.0,0,373450,8.0500,NaN,S
4,"Moran, Mr. James",0,3,1,male,NaN,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
885,"Montvila, Rev. Juozas",0,2,1,male,27.0,0,211536,13.0000,NaN,S
886,"Graham, Miss. Margaret Edith",1,1,1,female,19.0,0,112053,30.0000,B42,S
887,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,1,female,NaN,1,W./C. 6607,23.4500,NaN,S
888,"Behr, Mr. Karl Howell",1,1,1,male,26.0,0,111369,30.0000,C148,C
889,"Dooley, Mr. Patrick",0,3,1,male,32.0,0,370376,7.7500,NaN,Q

Making Data Frame from Dictionary

In [60]:
#Making Dictionary
o={"key1":[1,2,3,4,5],
   "key2":[6,7,8,9,10],
   "key3":[11,12,13,14,15]
   }

In [61]:
print(o)

{'key1': [1, 2, 3, 4, 5], 'key2': [6, 7, 8, 9, 10], 'key3': [11, 12, 13, 14, 15]}

In [65]:
#converting dictionary into data frame
pd.DataFrame(o)

   key1  key2  key3
0     1     6    11
1     2     7    12
2     3     8    13
3     4     9    14
4     5    10    15

In [70]:
t1=pd.read_csv("E:\OneDrive\Desktop\Data Analytics")

<>:1: SyntaxWarning: invalid escape sequence '\O'
<>:1: SyntaxWarning: invalid escape sequence '\O'
C:\Users\user\AppData\Local\Temp\ipykernel_5916\3259558304.py:1: SyntaxWarning: invalid escape sequence '\O'
  t1=pd.read_csv("E:\OneDrive\Desktop\Data Analytics")

PermissionError: [Errno 13] Permission denied: 'E:\\OneDrive\\Desktop\\Data Analytics'